title: 仲榮眞のポートフォリオ
email: nakaema@example.com
description: "ISTPタイプの落ち着いたエンジニアのポートフォリオ"
baseurl: "" # GitHub Pagesの場合は /リポジトリ名
url: "https://emachan92-dotcom.github.io" # 本番URL
theme: jekyll-theme-cayman

# ページの順序（トップページに表示順をコントロール）
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

